### ISSUE TITLE
Korean Educational Data 

### ISSUE THREAD

**Issue by jaykanglabor** [minvv23/hakbong-2021-preparation#5]
서울: 해당년도 데이터 미존재

경기: 신청중 

대구: 데이터가 있으나 학술대회용으로만 공개 가능하며 올해는 마감. 내년 3~4월경에 학술대회 할때나 지원 가능 

부산: 지금 신청이 가능하지만 12월부터 이용가능 (!?) 학술대회에 참여해주는 조건으로 드림. 

강원도: 종단연구 자체를 2011~2013에만 했고 지금은 도 단위에서는 수집하지않고있음.

**Comment by shkimecon** [comment]
Data lookup에 포함했어요. 이 이슈는 닫을까요?
